### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by thorus90** [froonix/acme-dns-nc#2]
Hi,

Your acme-dns-nc is working just fine, but the documentation to integrate it into acme.sh is wrong.

dns_fnx_nc.sh should look something like this:

```
#!/usr/bin/env sh

dns_fnx_nc_add() {
  fulldomain=$1
  txtvalue=$2
  _info "Using myapi"
  _debug fulldomain "$fulldomain"
  _debug txtvalue "$txtvalue"
  /usr/local/sbin/acme-dns-nc "$fulldomain" "$txtvalue"
  return $?
}

#Usage: fulldomain txtvalue
#Remove the txt record after validation.
dns_fnx_nc_rm() {
  fulldomain=$1
  txtvalue=$2
  _info "Using myapi"
  _debug fulldomain "$fulldomain"
  _debug txtvalue "$txtvalue"
  /usr/local/sbin/acme-dns-nc "$fulldomain"
  return $?
}
```

acme.sh expects it to be a shell script and have these two functions in it.

Regards,
thorus

**Comment by killerbees19** [comment]
Thanks, I'll update it in the next days.

btw: acme.sh has built-in support for netcup DNS-API. Take a look at https://github.com/acmesh-official/acme.sh/wiki/dnsapi#51-use-netcup-dns-api-to-automatically-issue-cert

**Comment by killerbees19** [comment]
These two functions are already included here: https://github.com/froonix/acme-dns-nc/blob/development/scripts/acme.sh-nc

This should work afaik, only the exit code is missing.
