### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by Netspider** [froonix/acme-dns-nc#5]
After upgrading to PHP 8.2 this script throws an error. It gives a possible solution but as I don't know php I cannot create a patch myself:

> Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator manual, Installer None
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for ronnylindner.de
Running manual-auth-hook command: acme-dns-nc/scripts/certbot-nc-auth
Error output from manual-auth-hook command certbot-nc-auth:
PHP Fatal error:  Uncaught ErrorException: SoapClient::__construct(): The "ssl_method" option is deprecated. Use "ssl" stream context options instead in acme-dns-nc/scripts/acme-dns-nc:253
Stack trace:
#0 [internal function]: error_handler()
#1 acme-dns-nc/scripts/acme-dns-nc(253): SoapClient->__construct()
#2 acme-dns-nc/scripts/acme-dns-nc(120): NCCCP->__construct()
#3 {main}
  thrown in acme-dns-nc/scripts/acme-dns-nc on line 253

> Waiting for verification...
Challenge failed for domain DOMAIN
dns-01 challenge for DOMAIN
Cleaning up challenges
Running manual-cleanup-hook command: acme-dns-nc/scripts/certbot-nc-cleanup
manual-cleanup-hook command "acme-dns-nc/scripts/certbot-nc-cleanup" returned error code 255
Error output from manual-cleanup-hook command certbot-nc-cleanup:
PHP Fatal error:  Uncaught ErrorException: SoapClient::__construct(): The "ssl_method" option is deprecated. Use "ssl" stream context options instead in acme-dns-nc/scripts/acme-dns-nc:253
Stack trace:
#0 [internal function]: error_handler()
#1 acme-dns-nc/scripts/acme-dns-nc(253): SoapClient->__construct()
#2 acme-dns-nc/scripts/acme-dns-nc(120): NCCCP->__construct()
#3 {main}
  thrown in acme-dns-nc/scripts/acme-dns-nc on line 253
Attempting to renew cert (DOMAIN) from renewal/DOMAIN.conf produced an unexpected error: Some challenges have failed.. Skipping.

**Comment by killerbees19** [comment]
Thanks! I'll prepare a patch...

https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.soap

**Comment by killerbees19** [comment]
@Netspider Workaround: Just remove the line with `ssl_method` :-)

https://github.com/froonix/acme-dns-nc/pull/6/files
